
spring:

  datasource:
    url: jdbc:h2:tcp://localhost/~/logintest
    driver-class-name: org.h2.Driver
    username: sa
    password: a
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace